Data Provider Page
transport-data/tdc-data-portal pull request #145
Opened 2024-10-11 12:47 UTC by muhammad-hassan11

2024-10-11 16:45 UTC, willy1989cv requested changes

2024-10-11 16:45 UTC, willy1989cv commented on frontend/src/components/data-provider/Hero.tsx
>              <Button className="mb-16 bg-[#006064] px-6 py-3.5">
have to set asChild=true to the <Button> component so it renders button properties on its first child, which is the <Link>

2024-10-11 16:45 UTC, willy1989cv commented on frontend/src/components/data-provider/AddDataSection.tsx
> +        <Button className="max-w-fit bg-[#006064] px-6 py-3.5">
have to set asChild=true to the component so it renders button properties on its first child, which is the <Link>

2024-10-11 16:45 UTC, willy1989cv commented on docs/data-provider/README.md
> +  "hero": {
if its supposed to use the same as Home page you should implement the video section as its in Home page. maybe create a component

2024-10-14 20:28 UTC, Gutts-n approved these changes
LGTM

2024-10-14 20:28 UTC, Gutts-n requested changes
.

2024-10-14 21:10 UTC, merged