Geography page implementation
transport-data/tdc-data-portal pull request #73
Opened 2024-09-10 18:59 UTC by Gutts-n

Related issue: https://github.com/transport-data/tdc-data-portal/issues/39

Created the map with this size because there is a problem with the width and zoom-out. if we add more width to the map and limit the maxZoom to 0.6 it breaks the canvas.

Another point is the gradient of the colors based on datasets, how will we implement it? Should we for every 193 (1650 / 9 tonalities of the cyan) dataset use a tonality of cyan?

2024-09-10 21:37 UTC, luccasmmg approved these changes
Im going to approve, but if im honest i think the client idea doesnt really work when you consider a real world map that needs to deal with things like Russia and little islands, i think a globe projection would probably look better but that would involve redoing everything and we dont have the time

https://docs.mapbox.com/mapbox-gl-js/example/add-image-generated/

2024-09-10 21:37 UTC, luccasmmg commented on frontend/src/pages/geography.tsx
> +      <Layout backgroundEffect>
Try playing with the backgroundEffect (There is a prop to change the percentage) curreently you can see a slight difference in the color 
![image](https://github.com/user-attachments/assets/3338cd40-e5f4-408b-a535-55586f00f1ef)

2024-09-10 21:37 UTC, luccasmmg commented on frontend/src/pages/geography.tsx
> +          stops: [
I think you can play around a little bit with these line-widths, i dont know if the other developers agree but on the mockup they seem smoother and i think thats in part cause of them being thicker
![image](https://github.com/user-attachments/assets/02c9c8b3-a4ef-49e6-9fc9-b4ed6bf9d931)
![image](https://github.com/user-attachments/assets/814f3375-ad52-427c-9034-03744b112a87)

2024-09-11 00:33 UTC, willy1989cv requested changes
- [ ] Tooltip
The flag should be full rounded as per figma
![image](https://github.com/user-attachments/assets/f0d55a19-2cf2-429a-83c3-de206a8722df)

- [ ] Map width should be the whole container width
![image](https://github.com/user-attachments/assets/05fe7941-d9fc-4023-a18c-bb3909c78537)

- [ ] Cards on Mobile should be 100% width
![image](https://github.com/user-attachments/assets/11299143-8c7b-42f4-816e-6dd1230a224e)

2024-09-11 01:05 UTC, Gutts-n commented
> * [ ]  Tooltip
>   The flag should be full rounded as per figma
>   ![image](https://private-user-images.githubusercontent.com/33525547/366257081-f0d55a19-2cf2-429a-83c3-de206a8722df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMTYxOTgsIm5iZiI6MTcyNjAxNTg5OCwicGF0aCI6Ii8zMzUyNTU0Ny8zNjYyNTcwODEtZjBkNTVhMTktMmNmMi00MjlhLTgzYzMtZGUyMDZhODcyMmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDAwNTEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyYzdhMDRmNTZlYjgzMzkxNzU1NmUzOGI2ODhhZGE2ZGQ3MTQ0NDU5ZWViYTdkYTEyYmMxNDcyMDRmZDNkOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AYqlQTFZyywz32a59kd8nI2Bl5i6Njl4BxDtisj5wpc)

@willy1989cv the API that I'm using to get the flags has images sliced in height, take a look at this endpoint https://flagsapi.com/US/flat/64.png, do you know some property to add to the img to stretch the image?

2024-09-11 01:21 UTC, willy1989cv commented
>  do you know some property to add to the img to stretch the image?

Try using object-fit. I tried in console, and used object-fit: none, it seems to work

2024-09-11 16:07 UTC, willy1989cv approved these changes
LGTM. the only thing I am not sure is. the countries with no datasets, should they show the tooltip as well?

2024-09-11 16:09 UTC, Gutts-n commented
> LGTM. the only thing I am not sure is. the countries with no datasets, should they show the tooltip as well?

Idk as well, I'll leave a comment to Uche and Osahon to check it

2024-09-11 16:10 UTC, merged