[FIX] Events Page: Upcoming and Past Events based on "from"-"to" fields
transport-data/tdc-data-portal pull request #97
Opened 2024-09-23 17:48 UTC by willy1989cv

Changes:
- Order Upcoming and Past Events based on "from"-"to" fields
- Set up a message when there are no upcoming events or past events to show on the events page
- Add a link to the events page to lead the user to an external page for the event. If there is no link to the event, don't show any link

2024-09-27 00:03 UTC, demenech requested changes

2024-09-27 00:03 UTC, demenech commented on frontend/.markdowndb/files.json
I suspect this file shouldn't be versioned

2024-09-27 12:34 UTC, willy1989cv commented on frontend/.markdowndb/files.json
fixed. @demenech

2024-09-29 16:26 UTC, demenech approved these changes
LGTM

2024-09-29 16:27 UTC, merged